package com.thinkfree.thinkchart.common.event;

public enum WsAction {
    USER_ASSIGNED,

    CURSOR_ENTER,
    CURSOR_MOVE,
    CURSOR_LEAVE,

    CIRCLE_DRAW_START,
    CIRCLE_DRAW_UPDATE,

    CIRCLE_CREATED,
    CIRCLE_UPDATED,
    CIRCLE_DELETED,
    CIRCLE_FOCUSED,

    CHART_CREATED,
    CHART_UPDATED,
    CHART_DELETED,

    CHART_BAR_UPDATED,
    CHART_BAR_DELETED
}
