name: ThinkChart CI/CD

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/*.jar

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-jar

      - name: Copy jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "*.jar"
          target: "/home/ubuntu/app"

      - name: Restart Spring Boot application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "===배포 시작==="
            cd /home/ubuntu/app
            
            chmod +x start.sh
            ./start.sh
            
            sleep 25
                        
            echo "===포트 확인==="
            sudo lsof -i:8080 || exit 1
            
            echo "===배포 성공==="
